spring:
  datasource:
    url: jdbc:postgresql://localhost:6060/musicLetter
    username: postgres
    password: posgre
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: enzoarauco@gmail.com
    password: password
    properties:
      mail:
        smtp:
          starttls:
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

security:
  security-realm: Spring Boot JWT
  signing-key: MaYzkSjmkzPC57L
  jwt:
    resource-ids: letterid

server:
  port: 7050
  error:
    include-message: always
  servlet:
    context-path: /api/back
